language: node_js
node_js:
- 11.10.1
dist: trusty
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run test
before_deploy:
- echo building...
- npm run build
deploy:
  provider: firebase
  token:
    secure: oRMIQBEVCwQG5vAyxm3HIDzsrdME4yZGZt9QrfIqpbnRFjGTRNthKS5pTB8ogkbP9b9AQzC/m/kW8nfJPqhDxTOVGnRVAnd+MzKQ3i4BUHxOxEptf17VuqZk8LEN+G32GCNx8qOon7wS0lAT7+CkLxkGWXtgJB50zD3iUOgJne+FDouKzZ4gdsJimO6okyEV4SNJICS4fxbJ1U/wogjlzvsciDKKaeRkj6ICNIdKcvpXQR9L07TpTrkCH9AdtmLp3UE7b18DNb9PfnN9kXIxvKwpwgFicQrmkzWcSXTqmbNPN6BLb2qer5BdjAr4x0qxC/4GaqHSadV8o/FDprZUJUlZ1S0Zmrwy5Rgvc2vYePjCDCdse8BYMvpQuqxdJFWj7VpnGXXYlkWJouQnXdlTrtrn1h+7iDWAisd02aNSu3j2MLOmMhtg1jxubNq6uobvkkofS4yL03dhcEvJRfIP8Xurz8joZWV95hLjsPkAML1v3CLSg8472TuxdFJUUTqyvowhGodZnYOlLI/JvYu7aRlOOjhgn0bdYcmunCk+DOQxQaCRHlAV8ywqbFq9hLltAsbU3dy+Mi0oRYN1GNZt/mTn7tQELA7JUnIrF9zGJdWLGqEHvpM3WTXMHhh7vglBf0gKbrOk5cemA8ARpeoKxSwx0GNO89p7A54npdecbh0=
  project: ifelsoncode
  skip_cleanup: true
after_deploy:
- echo deployed
after_success:
- echo done